TusClasificados/TusClasificados.Site/Models/Anuncio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TusClasificados.Site.Models
{
    public class Anuncio
    {
        public int Id { get; set; }
        public String Titulo { get; set; }
        public String Detalles { get; set; }
        public String NumeroTelefono { get; set; }
        public double Precio { get; set; }
        public String ExtraDetalles { get; set; }
        public TipoTicket TipoTicketUsado { get; set; }

        [Required]
        public virtual ApplicationUser Anunciante { get; set; }
        public virtual IEnumerable<Etiqueta> Etiquetas { get; set; }
        public virtual List<DateTimeWrapper> FechasAnuncio { get; set; }
    }

    public class DateTimeWrapper
    {
        public int Id { get; set; }
        public DateTime Value { get; set; }
    }
}

TusClasificados/TusClasificados.Site/Models/ViewModels/AnuncioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TusClasificados.Site.Models.ViewModels
{
    public class AnuncioViewModel
    {
        public String Titulo { get; set; }
        public String Detalles { get; set; }
        public String NumeroContacto { get; set; }
        public String Precio { get; set; }
        public String ExtraDetalles { get; set; }
        public String NombreAnunciante { get; set; }
        public TipoTicket TipoAnuncio { get; set; }
    }

    public class NuevoAnuncioViewModel
    {
        [Required(ErrorMessage = "Este campo es obligatorio")]
        public String Titulo { get; set; }
        [Required(ErrorMessage="Este campo es obligatorio")]
        [DataType(DataType.MultilineText)]
        public String Detalles { get; set; }
        [Required(ErrorMessage="Este campo es obligatorio")]
        [Display(Name="Numero de contacto")]
        public String NumeroContacto { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio")]
        public double Precio { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name="Información extra")]
        public String ExtraDetalles { get; set; }
        [Required(ErrorMessage = "Debes especificar el tipo de ticket que vas a utilizar")]
        [Display(Name="Tipo de ticket a usar")]
        public TipoTicket TicketUsar { get; set; }
        [Required(ErrorMessage="Debes especificar al menos una fecha para el anuncio")]
        [Display(Name="Fechas para anunciar")]
        public String FechasAnuncio { get; set; }

        public TicketCountViewModel TicketsDisponibles { get; set; }
    }

    public class TicketCountViewModel
    {
        public int BronzeTickets { get; set; }
        public int SilverTickets { get; set; }
        public int GoldTickets { get; set; }
    }
}

TusClasificados/TusClasificados.Site/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TusClasificados.Site.Infrastructure;
using TusClasificados.Site.Infrastructure.Services;
using TusClasificados.Site.Models;
using TusClasificados.Site.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace TusClasificados.Site.Controllers
{
    public class AnunciosController : BaseController
    {
        private readonly IAnunciosService _anunciosService;
        private readonly ICuentasService _cuentasService;
        private readonly IReloj _reloj;

        public AnunciosController(IAnunciosService anuncios, ICuentasService cuentas, IReloj reloj)
        {
            _anunciosService = anuncios;
            _cuentasService = cuentas;
            _reloj = reloj;
        }

        [HttpGet]
        [Authorize]
        public ActionResult NuevoAnuncio()
        {
            var currUser = UserManager.FindByEmail(User.Identity.Name);

            var model = new NuevoAnuncioViewModel
            {
                TicketsDisponibles = new TicketCountViewModel
                {
                    GoldTickets = currUser.Tickets.Where(t => t.TipoTicket == TipoTicket.Oro).ToList().Count,
                    SilverTickets = currUser.Tickets.Where(t => t.TipoTicket == TipoTicket.Plata).ToList().Count,
                    BronzeTickets = currUser.Tickets.Where(t => t.TipoTicket == TipoTicket.Bronze).ToList().Count,
                }
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult NuevoAnuncio(NuevoAnuncioViewModel model)
        {
            if (!ModelState.IsValid)
                return View("NuevoAnuncio", model);

            var fechasParsed = _anunciosService.ParseStringDatesToList(model.FechasAnuncio);

            var nuevoAnuncio = new Anuncio()
            {
                Titulo = model.Titulo,
                Detalles = model.Detalles,
                ExtraDetalles = model.ExtraDetalles,
                NumeroTelefono = model.NumeroContacto,
                Precio = model.Precio,
                TipoTicketUsado = model.TicketUsar,
                FechasAnuncio = fechasParsed
            };

            try
            {
                var currUser = UserManager.FindByEmail(User.Identity.Name);

                _anunciosService.AddAnuncio(nuevoAnuncio, currUser);
                _cuentasService.UsarTickets(nuevoAnuncio.TipoTicketUsado, nuevoAnuncio.FechasAnuncio.Count, currUser);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Ha ocurrido un error, intenta luego nuevamente.");
                return View("NuevoAnuncio", model);
            }
        }
    }
}

TusClasificados/TusClasificados.Site/Views/Anuncios/NuevoAnuncio.cshtml
@model TusClasificados.Site.Models.ViewModels.NuevoAnuncioViewModel
@{
    ViewBag.Title = "Nuevo Anuncio";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-8">
        @using(Html.BeginForm("NuevoAnuncio", "Anuncios", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.HiddenFor(m => m.TicketsDisponibles.BronzeTickets, new { @id = "bronzeTicketsAvailable" })
            @Html.HiddenFor(m => m.TicketsDisponibles.SilverTickets, new { @id = "silverTicketsAvailable" })
            @Html.HiddenFor(m => m.TicketsDisponibles.GoldTickets, new { @id = "goldTicketsAvailable" })

            @Html.AntiForgeryToken()
            <h4>Ingresa los datos del anuncio</h4>
            <hr />
            @Html.ValidationSummary(false)
            <div class="form-group">
                @Html.LabelFor(m => m.Titulo, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Titulo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Precio, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Precio, new { @class = "form-control", @type = "number" })
                    @Html.ValidationMessageFor(m => m.Precio, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.NumeroContacto, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.NumeroContacto, new { @class = "form-control", @type = "number" })
                    @Html.ValidationMessageFor(m => m.NumeroContacto, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Detalles, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Detalles, new { @class = "form-control", @rows = 3, maxlength = 200 })
                    @Html.ValidationMessageFor(m => m.Detalles, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ExtraDetalles, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.ExtraDetalles, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ExtraDetalles, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TicketUsar, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.TicketUsar, EnumHelper.GetSelectList(typeof(TusClasificados.Site.Models.TipoTicket)), "Selecciona el tipo de ticket", new { @class = "form-control", @id = "tipoTicket" })
                    @Html.ValidationMessageFor(m => m.TicketUsar, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-10" id="numeroTickets">
                    <label id="nTickets"></label>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.FechasAnuncio, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.FechasAnuncio, new { @id = "datepicker", @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.FechasAnuncio, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-10" id="numeroTickets">
                    <label id="nTickets"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-default btn-block" />
                </div>
            </div>
        
        }
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            

            actualizarTicketsLabel();

            $('#tipoTicket').change(function () {
                actualizarTicketsLabel();
            });
        });

        var actualizarTicketsLabel = function () {
            $('#nTickets').hide();
            $('#datepicker')
                .fadeOut()
                .val('')
                .multiDatesPicker('destroy');

            var tipo = $('#tipoTicket').val();
            var resultado;
            var tickets;

            if (tipo == 0) {
                tickets = $('#bronzeTicketsAvailable').val();
                resultado = "Tienes " + tickets + " tickets Bronze disponibles.";
            } else if (tipo == 1) {
                tickets = $('#silverTicketsAvailable').val();
                resultado = "Tienes " + tickets + " tickets Plata disponibles.";
            } else if (tipo == 2) {
                tickets = $('#goldTicketsAvailable').val();
                resultado = "Tienes " + tickets + " tickets Oro disponibles.";
            }

            var today = new Date();
            console.log(today.toString());
            $('#datepicker').multiDatesPicker({
                maxPicks: tickets,
                minDate: 0
            })
                .fadeIn();

            $('#nTickets').text(resultado).show();
        }
    </script>
}